const state={data:null,audit:[]};
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
async function loadData(){const r=await fetch('../data/demo-data.json');state.data=await r.json();state.audit=[...state.data.audit];renderAll();}
function logAction(text){state.audit.unshift({time:new Date().toLocaleString('tr-TR'),text});renderAudit();toast(text)}
function toast(text){const el=qs('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function renderAll(){const d=state.data;qs('#assetCount').textContent=d.assets.length;qs('#incidentCount').textContent=d.incidents.filter(x=>x.status!=='Çözüldü').length;qs('#criticalCount').textContent=d.incidents.filter(x=>x.severity==='Kritik'&&x.status!=='Çözüldü').length;qs('#meshHealth').textContent=d.meshHealth+'%';qs('#lastUpdated').textContent='Güncelleme: '+new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'});renderRisk();renderRecent();renderRecommendation();renderGraph();renderIncidents();renderAssets();renderAudit();}
function renderRisk(){const counts={Kritik:0,Yüksek:0,Orta:0,Düşük:0};state.data.incidents.forEach(x=>counts[x.severity]++);const max=Math.max(...Object.values(counts),1);qs('#riskBars').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="track"><div class="fill ${k==='Kritik'?'critical':k==='Yüksek'?'warn':'safe'}" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join('')}
function renderRecent(){qs('#recentIncidents').innerHTML=state.data.incidents.slice(0,4).map(x=>`<div class="incident"><i class="severity ${sevClass(x.severity)}"></i><div><b>${x.title}</b><small>${x.asset} · ${x.time}</small></div><span class="tag">${x.status}</span></div>`).join('')}
function renderRecommendation(){const critical=state.data.incidents.find(x=>x.severity==='Kritik'&&x.status!=='Çözüldü');qs('#recommendationTitle').textContent=critical?`${critical.asset} varlığını izole edin`:'Kritik aksiyon gerekmiyor';qs('#recommendationText').textContent=critical?`${critical.title} olayı için lateral hareket ihtimalini azaltmak üzere düğümü geçici olarak karantinaya alın.`:'Mesh sağlıklı görünüyor. Periyodik yerel taramaya devam edin.'}
function sevClass(s){return s==='Kritik'?'critical':s==='Yüksek'?'high':s==='Orta'?'medium':'low'}
function renderGraph(){const el=qs('#attackGraph');el.innerHTML='';const nodes=state.data.graph.nodes;const edges=state.data.graph.edges;edges.forEach(([a,b])=>{const n1=nodes.find(n=>n.id===a),n2=nodes.find(n=>n.id===b);const box=el.getBoundingClientRect();const x1=n1.x/100*box.width,y1=n1.y/100*box.height,x2=n2.x/100*box.width,y2=n2.y/100*box.height;const len=Math.hypot(x2-x1,y2-y1),angle=Math.atan2(y2-y1,x2-x1)*180/Math.PI;const edge=document.createElement('div');edge.className='edge';edge.style.cssText=`left:${x1}px;top:${y1}px;width:${len}px;transform:rotate(${angle}deg)`;el.appendChild(edge)});nodes.forEach(n=>{const x=document.createElement('button');x.className=`node ${n.status}`;x.style.left=n.x+'%';x.style.top=n.y+'%';x.textContent=n.label;x.onclick=()=>qs('#nodeDetail').innerHTML=`<b>${n.label}</b> — ${n.detail}`;el.appendChild(x)})}
function renderIncidents(){qs('#incidentTable').innerHTML=`<table class="table"><thead><tr><th>Olay</th><th>Varlık</th><th>Seviye</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>${state.data.incidents.map((x,i)=>`<tr><td>${x.title}</td><td>${x.asset}</td><td>${x.severity}</td><td>${x.status}</td><td><button class="mini-btn" onclick="resolveIncident(${i})">${x.status==='Çözüldü'?'Yeniden Aç':'Çöz'}</button></td></tr>`).join('')}</tbody></table>`}
window.resolveIncident=i=>{const x=state.data.incidents[i];x.status=x.status==='Çözüldü'?'İnceleniyor':'Çözüldü';logAction(`${x.title}: durum ${x.status}`);renderAll()}
function renderAssets(){qs('#assetGrid').innerHTML=state.data.assets.map(x=>`<div class="asset"><div class="asset-top"><b>${x.name}</b><span class="tag">${x.type}</span></div><p>${x.ip} · ${x.status}</p><div class="health"><span style="width:${x.health}%"></span></div><p>Sağlık: ${x.health}%</p></div>`).join('')}
function renderAudit(){qs('#auditLog').innerHTML=state.audit.map(x=>`<div class="audit-entry"><time>${x.time}</time><div>${x.text}</div></div>`).join('')}
qsa('.nav').forEach(btn=>btn.onclick=()=>{qsa('.nav').forEach(x=>x.classList.remove('active'));btn.classList.add('active');qsa('.view').forEach(x=>x.classList.remove('active'));qs('#'+btn.dataset.view).classList.add('active');qs('#pageTitle').textContent=btn.textContent;if(btn.dataset.view==='graph')setTimeout(renderGraph,20)});
qs('#scanBtn').onclick=()=>{qs('#scanBtn').disabled=true;qs('#scanBtn').textContent='Taranıyor…';setTimeout(()=>{state.data.meshHealth=Math.min(100,state.data.meshHealth+1);logAction('Yerel mesh taraması tamamlandı');qs('#scanBtn').disabled=false;qs('#scanBtn').textContent='Yerel Tarama Başlat';renderAll()},1200)}
qs('#applyRecommendation').onclick=()=>{const target=state.data.assets.find(x=>x.name==='DB-PROD-01')||state.data.assets[0];target.status='Karantinada';target.health=Math.max(40,target.health-20);logAction(`${target.name} geçici karantinaya alındı`);renderAll()}
qs('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({generatedAt:new Date().toISOString(),...state.data,audit:state.audit},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sentinel-mesh-report.json';a.click();URL.revokeObjectURL(a.href);logAction('Yerel güvenlik raporu dışa aktarıldı')}
window.addEventListener('resize',()=>{if(qs('#graph').classList.contains('active'))renderGraph()});
loadData().catch(()=>{document.body.innerHTML='<div style="padding:40px;font-family:sans-serif"><h2>Uygulama doğrudan dosyaya çift tıklanarak açılamaz.</h2><p>Lütfen START-MAC.command veya START-WINDOWS.bat dosyasını çalıştırın.</p></div>'});
